(function(){ovi.provide("nokia.maps.map.HitArea");
(function(){var f=Math,e=f.PI/180,c=f.ceil,b=f.min,a=f.sin,h=f.cos,d=nokia.maps.util,i=nokia.maps.map.HitArea=new ovi.Class({initialize:function(i,g){var f=(g=[].concat(g)).length,k=f,j,n,p,o,r;this.values=g;for(this.type=i;k--;)isNaN(g[k]=g[k])&&d.f("Given argument is not the array of numbers");i==="rect"&&f>3&&(g=[+g[0],+g[1],+g[2],+g[1],+g[2],+g[3],+g[0],+g[3]],i="poly");if(i==="circle"&&f>2&&(p=+g[2])>0){j=+g[0];n=+g[1];k=b(c(p)*2,40);o=360/k;for(g=[];k--;)r=o*k*e,g.push(j+a(r)*p,n+h(r)*p);i=
"poly"}if(i==="poly"&&f&&!(g.length%2))this.Ua=g;!this.Ua&&d.f("bad polygon")},Statics:{from:function(a){return a instanceof i?a:new i(a.type,a.values?a.values:a.coords)}},hitTest:function(a,b){return a.isCoveredBy(this.Ua,b,1)}})})();ovi.provide("nokia.maps.util.math.douglasPeucker");
(function(f){var e=Math,c=e.min,b=e.abs,a=e.sqrt,h=e.pow,d=f.douglasPeucker=function(e,f,g,m,k){m===void 0&&(m=0,k=e.length-2);for(var j,n=0,p=m,o=e[m],r=e[m+1],q=e[k],s=e[k+1],w=m+2,v,u=(s-r)/(q-o)||0;w<k;)if(j=e[w++],v=e[w++],n<(j=c(b(v-u*j-(r-u*o))/a(h(u,2)+1),a(h(j-o,2)+h(v-r,2)),a(h(j-q,2)+h(v-s,2)))))n=j,p=w-2;n>=f||g>0?(m=d(e,f,g=(g||0)-1,m,p),m.splice(m.length-2,2),m=m.concat(d(e,f,g,p,k))):m=[e[m],e[m+1],e[k],e[k+1]];return m}})(nokia.maps.util.math);ovi.provide("nokia.maps.util.ColorHelper");
(function(f){function e(a){var d;if(a.charAt(0)==="#")d=i[a.length]?a:null;else if(a.substr(0,3)==="rgb"){d=a.match(/\d+(\.\d+)?/g);var c=d.length;d=c>2&&c<5?["#",b(+d[0]),b(+d[1]),b(+d[2]),c>3?b(+d[3]*255):"ff"].join(""):null}d||f.f("Invalid color definition: "+a);return d}function c(a){return!/^(#|rgb).*/.test(a)}function b(a){return a<16?"0"+h(a).toString(16):h(a).toString(16)}function a(a){a=d(a,16);return(a<<4)+a}var h=Math.round,d=parseInt,i={4:function(a){return["#",a.charAt(1),a.charAt(1),
a.charAt(2),a.charAt(2),a.charAt(3),a.charAt(3),"ff"].join("")},5:function(a){return["#",a.charAt(1),a.charAt(1),a.charAt(2),a.charAt(2),a.charAt(3),a.charAt(3),a.charAt(4),a.charAt(4)].join("")},7:function(a){return a+"ff"},9:function(a){return a}},l={4:function(b){return[a(b.charAt(1)),a(b.charAt(2)),a(b.charAt(3)),255]},5:function(b){return[a(b.charAt(1)),a(b.charAt(2)),a(b.charAt(3)),a(b.charAt(4))]},7:function(a){a=d(a.substring(1),16);return[a>>16&255,a>>8&255,a&255,255]},9:function(a){a=d(a.substring(1),
16);return[a>>24&255,a>>16&255,a>>8&255,a&255]}};f.ColorHelper={toInternal:function(a){return c(a)?a:(a=e(a),i[a.length]?i[a.length](a):a)},toRGBA:function(a,b){return c(a)?[0,0,0,255]:(b||(a=e(a)),l[a.length](a))},getHex3:function(a,b){return c(a)?a:(b||(a=e(a),a=i[a.length]?i[a.length](a):a),a.substr(0,7))},getAlpha:function(a,b){return c(a)?1:(b||(a=e(a),a=i[a.length]?i[a.length](a):a),d(a.substr(7,2),16)/255)},toRandomRGBA:function(a,d){if(c(a))return"000000ff";else{for(var a=this.toRGBA(a,d),
e=0;e<4;e++)a[e]=""+b(e<3?Math.floor(Math.random()*(a[e]-0+1))+0:a[e]);return a.join("")}}}})(nokia.maps.util);ovi.provide("nokia.maps.map.component.Copyright");(function(f){f.map.component.Copyright=new ovi.Class({Extends:f.map.component.Component,initialize:function(e){this._super(e)},d:"Copyright",A:"0.0.0.1",attach:function(e){this._super(e)},detach:function(e){this._super(e)},setPosition:function(e){this.mapDisplay.set("copyrightAlignment",e)}})})(nokia.maps);ovi.provide("nokia.maps.map.component.panning.Click");
(function(f){var e=f.map.component;e.panning.Click=new ovi.Class({Extends:e.Component,d:"panning.Click",A:"0.0.0.1",initialize:function(c){function b(b){a.enabled&&(d.getComponentById("panning.Kinetic"),d.pan(0,0,-(d.width/2-b.displayX),-(d.height/2-b.displayY)))}var a=this,h=e.Component.prototype,d;a._super(ovi.extend({enabled:!0,useKineticPanning:!0},c));a.attach=function(c){h.attach.call(a,c);d=c;d.addListener("click",b)};a.detach=function(c){h.detach.call(a,c);d.removeListener("click",b)}}})})(nokia.maps);
ovi.provide("nokia.maps.map.component.panning.KineticMovement");
(function(f){var e=f.map.component,c=f.util,b=c.now,a=c.math.douglasPeucker,h=Math.sqrt,d=c.Vector3D,i=c.Coroutine;e.panning.KineticMovement=new ovi.Class({Extends:f.util.OObject,initialize:function(a,c,h){if(!(h instanceof e.panning.Kinetic))throw"Can't instantiate abstract class KineticMovement!";c=c||b();this._super(ovi.extend({fraction:3.5,fractionHz:10,maxFps:25,fps:0,frames:0,direction:new d(0,0,0),speed:0,enabled:!0,movementPhase:!0,slidingPhase:!1,finished:!1,aborted:!1},a));this.owner=h;
this.gh=[];this.Ms=this.We=c;this.Ve=0;this.Xc=c;this.updateSpeedLimits()},updateSpeedLimits:function(){var a=this.owner.mapDisplay;a&&(a=h(a.width*a.width+a.height*a.height),this.set("stopSpeed",a*0.05),this.set("minSpeed",a*0.1),this.set("maxSpeed",a*1))},moveBy:function(a,d,c,e){var h=this.gh,e=(e=+e)===e?e:b();if(e-this.Xc>250)h.length=0;this.Xc=e;h.push({time:e,dx:a,dy:d});h.length>300&&h.splice(0,50);c&&this.enabled&&this.owner.mapDisplay.pan(0,0,a,d);return this},endMovement:function(c){if(!this.movementPhase)return this;
var c=(c=+c)===c?c:b(),e=c-250,f=this.gh,k=[],j=0,n=c,p,o=0,r=0,q=0;this.updateSpeedLimits();for(q=f.length-1;q>=0;q--)if(p=f[q],p.time>e)k.push(p.dx,p.dy),j+=h(p.dx*p.dx+p.dy*p.dy),n=p.time;else break;f.length=0;if(!k.length)return this.set("speed",0),this.set("direction",0),this.set("movementPhase",!1),this.set("slidingPhase",!1),this;q=j/(c-n||1.0E-9)*1E3;if(q>this.maxSpeed)q=this.maxSpeed;if(q<this.minSpeed)q=this.minSpeed;this.set("speed",q);k=a(k,20);q=0;for(e=k.length;q<e;)o+=k[q++],r+=k[q++];
this.set("direction",(new d(o,r,0)).normalize());this.set("movementPhase",!1);this.set("slidingPhase",!0);this.Ve=c;i.resume(this.owner.ee);return this},stop:function(a,d){var c=d===!1;if(this.aborted)return this;a=a||b();this.set("movementPhase",!1);this.set("slidingPhase",!1);this.set("lastUpdate",a);this.set("fps",this.frames/((a-this.Ve)/1E3));this.set("finished",!0);this.set("aborted",c);this.set("speed",0);i.resume(this.owner.ee);return this}})})(nokia.maps);ovi.provide("nokia.maps.map.component.panning.Tap");
(function(f){var e=f.map.component;e.panning.Tap=new ovi.Class({Extends:e.Component,d:"panning.Tap",A:"0.0.0.1",initialize:function(c){function b(b){a.enabled&&(d.getComponentById("panning.Kinetic"),d.pan(0,0,-(d.width/2-b.displayX),-(d.height/2-b.displayY)))}var a=this,h=e.Component.prototype,d;a._super(ovi.extend({enabled:!0,useKineticPanning:!0},c));a.attach=function(c){h.attach.call(a,c);d=c;d.addListener("tap",b)};a.detach=function(c){h.detach.call(a,c);d.removeListener("tap",b)}}})})(nokia.maps);
ovi.provide("nokia.maps.map.component.zoom.DoubleClick");
(function(f){var e=f.map.component;e.zoom.DoubleClick=new ovi.Class({Extends:e.Component,d:"zoom.DoubleClick",A:"0.0.0.1",initialize:function(){function c(b){a.enabled&&((i=h.getComponentById("panning.Kinetic"))&&i.set("current",null),h.setZoomLevel(h.zoomLevel+(b.button===2?-1:1),"default",b.displayX,b.displayY),b.cancel())}function b(b){a.enabled&&b.preventDefault()}var a=this,h,d=e.Component.prototype,i;a._super({enabled:!0});a.attach=function(e){d.attach.call(a,e);h=e;h.addListener("dblclick",
c);h.addListener("contextmenu",b)};a.detach=function(e){d.detach.call(a,e);h.removeListener("dblclick",c);h.removeListener("contextmenu",b)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.zoom.DoubleTap");
(function(f){var e=f.map.component;e.zoom.DoubleTap=new ovi.Class({Extends:e.Component,d:"zoom.DoubleTap",A:"0.0.0.1",initialize:function(){function c(d){b.enabled&&((h=a.getComponentById("panning.Kinetic"))&&h.set("current",null),a.setAttributes("default",a.pixelToGeo(d.displayX,d.displayY),a.zoomLevel+1),d.cancel())}var b=this,a,h,d=e.Component.prototype;b._super({enabled:!0});b.attach=function(e){d.attach.call(b,e);a=e;a.addListener("dbltap",c)};b.detach=function(e){d.detach.call(b,e);a.removeListener("dbltap",
c)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.zoom.GestureEvent");
(function(f){var f=f.map.component,e,c,b=ovi.Array.forEach,a=ovi.Array.indexOf,h=f.Component.prototype,d=["gesturestart","gestureend","gesturechange"];f.zoom.GestureEvent=new ovi.Class({Extends:f.Component,d:"zoom.GestureEvent",A:"0.0.0.1",initialize:function(){c=this;c._super();c.attach=function(a){h.attach.call(c,a);e=a;b(d,function(a){e.addEvent(a)})};c.detach=function(a){h.detach.call(c,a);b(d,function(a){e.removeEvent(a)})}},addListener:function(b,c){if(a(d,b)>=0)return e.addListener(b,c),!0;
return!1},removeListener:function(b,c){if(a(d,b)>=0)return e.removeListener(b,c),!0;return!1}})})(nokia.maps);ovi.provide("nokia.maps.map.component.zoom.MouseWheel");
(function(f){f.map.component.zoom.MouseWheel=new ovi.Class({Extends:f.map.component.Component,d:"zoom.MouseWheel",A:"0.0.0.1",initialize:function(){function e(a){c.enabled&&(b.setZoomLevel(b.zoomLevel+a.wheelDelta,"default",a.displayX,a.displayY),a.cancel())}var c=this,b,a=f.map.component.Component.prototype;c._super({enabled:!0});c.attach=function(h){a.attach.call(c,h);b=h;b.addListener("mousewheel",e)};c.detach=function(h){a.detach.call(c,h);b.removeListener("mousewheel",e)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.panning.Kinetic");
(function(f){var e=f.map.component,c=e.panning,f=f.util,b=f.Coroutine;if(!f.getConstructor(c.Kinetic))c.Kinetic=new ovi.Class({Extends:e.Component,d:"panning.Kinetic",A:"0.0.0.1",initialize:function(a){this._super(ovi.extend({current:c},a));var c=null,d=this,i=c,f=0,g=0,m=0,k=0,j=0,n=this.Fm=b.create("nokia.maps.map.component.panning.Kinetic#slidingCo",function(a,d){var c=a.that,e=d.callTime,h,n;if(i!==c.current)i=c.current,m=f=g=k=j=0;if(!i||!i.slidingPhase)return b.sleep();if(!m)return m=1E3/i.maxFps,
f=e+m,g=e,k=j=0,b.sleep(m);if(e<f)return b.sleep(f-e);h=i.speed;if(h>p.maxSpeed)h=p.maxSpeed;h*=(e-g)/1E3;k+=h*i.direction.x;j+=h*i.direction.y;if(Math.abs(k)>=1||Math.abs(j)>=1)h=Math.floor(k),n=Math.floor(j),k-=h,j-=n,c.mapDisplay.pan(0,0,h,n);i.set("frames",i.frames+1);i.set("fps",i.frames/((e-i.Ve)/1E3));g=e;f=e+m;return b.sleep(m)},{priority:100,useAnimationFrame:!0}).call(this),p=c,o=0,r=0,q=this.ee=b.createEx("nokia.maps.map.component.panning.Kinetic#fractionCo",function(a,e){var g,i;if(p!==
d.current)p=d.current,o=r=0,b.resume(n);if(!p||!p.slidingPhase)return b.sleep();if(!o)return o=e.callTime,r=1E3/p.fractionHz,b.resume(n),b.sleep(r);if((i=r-((g=e.callTime)-o))>0)return b.sleep(i);b.resume(n);o=g;p.updateSpeedLimits();g=i=p.speed;if(i<p.minSpeed)i=p.minSpeed;g-=i*p.fraction/p.fractionHz;g<=p.stopSpeed&&(g=0);p.set("speed",g);if(g===0)return p.stop(c,!0),d.set("current",p=c),b.sleep();return b.sleep(r)},{priority:100}).call(this);n.set("priority",100);q.set("priority",100);d.addObserver("current",
function(a,d,c,e){if(c!==e&&(e&&e.set("enabled",!1),c)){if(c.finished)throw"Failed to reactivate already finished kinetic movement!";c.set("enabled",!0);b.resume(q)}},d);d.startMovement=function(a){a=new e.panning.KineticMovement(null,a,d);d.set("current",a);return a}},destroy:function(){b.kill(this.ee);b.kill(this.Fm)}})})(nokia.maps);ovi.provide("nokia.maps.map.component.zoom.Gesture");
(function(f){var e=f.map.component;e.zoom.Gesture=new ovi.Class({Extends:e.Component,d:"zoom.Gesture",A:"0.0.0.1",initialize:function(){function c(a){if(h.enabled){if(i){if(j)f=a.scale;k&&(g=m+a.rotation);q=r;for(var b=!1,c=!1;f>=2;)f/=2,q++,b=!0;for(;f<=0.75;)f*=2,q--,c=!0;!b&&f>1.1&&q++;!c&&f<0.9&&q--;d.transform(void 0,void 0,g,1);k&&(g=m+a.rotation,g>=-9&&g<=9&&(g=0),d.set("heading",g));q!==d.zoomLevel&&d.set("zoomLevel",q)}a.preventDefault()}}function b(a){if(h.enabled){if(i){if(j)f=a.scale;
k&&(g=m+a.rotation);q!==d.zoomLevel&&d.set("zoomLevel",q);d.transform(void 0,void 0,g,f);d.forceTileRender()}else{var b=a.rotation;f=a.scale;Math.abs(v-f)>0.1&&!p&&(o=!0);d.maxHeading!=0&&Math.abs(w-b)>5&&!o&&(p=!0);p&&d.set("heading",360-b-5);o&&(b=v>f?u-3*(f-0.1):u+3/(f-0.1),b!==x&&d.setAttributes("default",s,x=b))}a.preventDefault()}}function a(a){if(h.enabled)i?(q=r=d.zoomLevel,g=m=d.heading,f=1):(o=p=!1,s=d.center,w=0,v=1,x=u=d.zoomLevel),a.preventDefault()}var h=this,d,i,f=0,g=0,m,k=!1,j=!0,
n=e.Component.prototype,p=!1,o=!1,r,q,s,w,v,u,x,z;h._super({enabled:!0});h.attach=function(g){n.attach.call(h,g);d=g;z=new e.zoom.GestureEvent;d.addComponent(z);z.addListener("gesturestart",a);z.addListener("gesturechange",b);z.addListener("gestureend",c);d.Ui&&(i=!0)};h.detach=function(e){n.detach.call(h,e);d.removeComponent(z);z.removeListener("gesturestart",a);z.removeListener("gesturechange",b);z.removeListener("gestureend",c)};h.enableRotation=function(){};h.disableRotation=function(){k=!1};
h.enableZoom=function(){j=!0};h.disableZoom=function(){j=!1}}})})(nokia.maps);ovi.provide("nokia.maps.map.Object");
(function(){var f=0,e=0,c={rev:0,comparator:function(b){return function(a,c){for(var d=a.ha(b),i=c.ha(b),f=d.length,g=i.length,m=f<g?f:g,k=0,j;k<m;k++)if(j=i[k]-d[k])return e?-j:j;return e?f-g:g-f}},sort:function(b,a,c,d){for(var i=[],f=a.yd,g,m=b.length;m--;)((g=b[m]).getIconForRendering||g.drawToTile)&&(c||g.isVisible(a))&&i.push(g);e=d;i.sort(f);return i},create:function(b,a){var c=b.getParent(a),d;d=null;c&&(d=(d=c!==a?c.ha(a):null)?d.slice():[],d.push(b.zIndex,c.objects.indexOf(b)));return d}};
nokia.maps.map.Object=new ovi.Class({Extends:nokia.maps.util.OObject,Mixins:[nokia.maps.dom.EventTarget],Statics:{sortByZInfo:c.sort},initialize:function(b){this.d=f++;this.u={};this._super(b);this.addObserver("*",this.aa,this);if(this.q==="display")this.yd=c.comparator(this)},destroy:function(){for(var b=this.getDisplays(),a=b.length,c;a--;)b[a].objects.remove(this);if(b=this.eventListener)for(c in b)for(;b[c]&&b[c].length>0;)a=b[c],this.removeListenerNS(a[2],c,a[0],a[1]);this.removeObserver("*",
this.aa,this);this.u=null},CHANGE_SPATIAL:1,CHANGE_VISUAL:2,CHANGE_ZINDEX:4,isEventTarget:!0,zIndex:0,visibility:!0,q:"object",Y:2147483647,qf:-1/0,aa:function(b,a,c){this.Z(a,c,this.Y|=a==="zIndex"&&4)},getDisplays:function(){var b=this.u,a=[],c;for(c in b)b.hasOwnProperty(c)&&a.push(b[c].N);return a},isAdded:function(b){return this.u.hasOwnProperty(b.d)},getParent:function(b){return(b=b&&this.u&&this.u[b.d])&&b.B},isVisible:function(b){var a=this,c;do c=a.visibility;while(c&&(a=a.getParent(b)));
return c},Z:function(b,a,c){for(var d=this.getDisplays(),e=d.length;e--;)d[e].Cb(this,b,a,c,0);this.Y=0},zIndexSetter:function(b){this.lb();return b},eventListenerSetter:function(b){var a;a=0;var c,d;if(b){if(a=this.eventListener)for(d in a)for(;a[d]&&a[d].length>0;)c=a[d],this.removeListenerNS(c[2],d,c[0],c[1]);for(d in b)if((a=ovi.type(c=b[d]))==="array")for(a=0;a<c.length;a+=3)this.addListenerNS(c[a+2],d,c[a],c[a+1]);else a==="function"&&this.addListenerNS(null,d,c,!1)}return this.eventListener},
ha:function(b){var a=this.u[b.d],e;if(!(e=a.$a))e=a.$a=c.create(this,b);return e},lb:function(){var b=this.u,a;for(a in b)if(b.hasOwnProperty(a))b[a].$a=void 0}})})();ovi.provide("nokia.maps.map._MarkerIcon");
(function(){function f(a){if(typeof a==="object"&&a.strokeColor)a.strokeColor=b.ColorHelper.getHex3(a.strokeColor);if(a instanceof h)return a;else if(typeof a==="object")return new h(a);return new h({strokeColor:b.ColorHelper.getHex3(a)})}var e=nokia.maps,c=e.map.HitArea,b=e.util,a=b.Point,h=b.Pen,d=b.Brush,i=e.gfx.GraphicsImage,l=new e.gfx.SvgParser,g=b.ac("shape text textPen pen brush effect"),m=b.flatMerge(b.ac("anchor hitArea"),g),k=nokia.maps.map.Ra=new ovi.Class({Extends:nokia.maps.util.OObject,
initialize:function(a){var b;a&&"shape"in a?(this.shape=this.shapeSetter(b=a.shape),delete a.shape,this._super(a),a.shape=b):(this.shape=this.shapeSetter(this.shape),this._super(a));this.addObserver("*",this.Sc)},Statics:{Ej:m,ra:function(a){return a in m},dd:function(a){return!(a in g)},Va:{balloon:['<path style="opacity:0.4;fill:#353535" d="m 68.999,117 c 0,1.668 -2.687,3 -6.001,3 c -3.312,0 -5.999,-1.332 -5.999,-3 c 0,-1.666 2.688,-3 5.999,-3 c 3.314,0 6.001,1.334 6.001,3 z" transform="translate(-50,-86)"/><path style="fill:__PEN__" d="m 106,-21 c -3.472,0 -6.7335,1.325 -9.1875,3.75 C 94.3585,-14.824 93,-11.58625 93,-8.15625 c 0,3.432 1.3585,6.6385 3.8125,9.0625 L 106,10 l 9.1875,-9.09375 c 2.455,-2.426 3.8125,-5.6325 3.8125,-9.0625 c 0,-3.428 -1.3575,-6.66575 -3.8125,-9.09375 C 112.7325,-19.675 109.474,-21 106,-21 z" transform="translate(-93,21)"/><path style="fill:#ffffff" d="m 106,-20 c -3.207,0 -6.234,1.22975 -8.5,3.46875 c -2.264,2.237 -3.5,5.217 -3.5,8.375 c 0,3.16 1.236,6.139 3.5,8.375 l 8.5,8.375 l 8.5,-8.375 c 2.264,-2.236 3.5,-5.215 3.5,-8.375 c 0,-3.158 -1.236,-6.137 -3.5,-8.375 C 112.233,-18.77025 109.209,-20 106,-20 z" transform="translate(-93,21)"/><path style="fill:__BRUSH__;fill-opacity:1" d="m 62.998,88.1875 c -6.984391,0 -10.738298,4.963982 -10.8105,10.6525 c 0,3.268 0.9535,5.611 3.0255,7.658 l 7.785,7.691 l 7.789,-7.691 c 2.072,-2.047 3.0255,-4.268 3.0255,-7.658 C 73.584296,93.067975 69.982391,88.1875 62.998,88.1875 z" transform="translate(-50,-86)"/><text x="13" y="18" font-size="10pt" font-family="arial" font-weight="bold" text-anchor="middle" fill="__TEXTPEN__" textContent = "__TEXTCONTENT__">__TEXT__</text>',
28,36,13,31,"poly",[0,16,0,7,8,0,18,0,26,7,26,16,18,34,8,34]]}},text:"",pen:new h({strokeColor:"#FFF"}),textPen:new h({strokeColor:"#FFF"}),brush:new d({color:"#1080DD"}),shape:"balloon",effect:"none",Sc:function(a,b){if(b in g)a.pa=0},shapeSetter:function(d){var e=this.Mj=k.Va[d]||b.f("shape");this.j=new a(e[1],e[2]);this.anchor=new a(e[3],e[4]);this.hitArea=e[5]?new c(e[5],e[6]):void 0;return d},brushSetter:function(a){if(typeof a==="object"&&a.color)a.color=b.ColorHelper.getHex3(a.color);if(a instanceof
d)return a;else if(typeof a==="object")return new d(a);return new d({color:b.ColorHelper.getHex3(a)})},penSetter:f,textPenSetter:f,textSetter:function(a){return b.sanitizeText(a)},getIcon:function(){if(this.pa)return this.pa;var a=k.Va[this.shape],b=a[1],d=a[2];return this.pa=new i(l.parseSvg('<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="'+b+'" height="'+d+'" viewBox="0 0 '+b+" "+d+'">'+a[0].replace("__TEXTCONTENT__",this.text).replace("__TEXT__",this.text).replace("__TEXTPEN__",this.textPen.strokeColor).replace("__PEN__",
this.pen.strokeColor).replace("__BRUSH__",this.brush.color)+"</svg>"))}})})();ovi.provide("nokia.maps.map.Marker");
(function(){var f=nokia.maps,e=f.util,c=f.dom,b=f.gfx,a=e.Point,h=e.Strip,d=new a(0,0),i=e.Rectangle,l=f.map.Ra,g=f.geo,m=f.map.HitArea,k=g.Coordinate,f=new ovi.Class({Extends:nokia.maps.map.Object,initialize:function(a,b){var d;if(this.q==="marker"&&(!b||!("icon"in b)))d=new l,this.set("icon",d.getIcon()),this.set("anchor",d.anchor),this.set("hitArea",d.hitArea);this.qa={};this._super(b);this.set("coordinate",a,1)},q:"marker",anchor:d,j:d,coordinateSetter:function(a){(a=k.fromObject(a))||e.f();this.qa=
{};return a},hitAreaSetter:function(a){return!a?a:m.from(a)},anchorSetter:function(b){(b=a.fromObject(b))||e.f("you have to set util.Point");return b},iconSetter:function(d){ovi.type(d);d instanceof b.Image||(d=b.Image.fromObject(d));d instanceof b.Image||e.f("icon");this.icon=d.F===document?d:d.clone(document);this.j=new a(d.width,d.height);return this.icon},getBoundingBox:function(){return g.BoundingBox.coverAll([this.coordinate])},getDisplayBoundingBox:function(a){this.isAdded(a)||e.f("the map object is not added to the given display");
a=a.geoToPixel(this.coordinate).sub(this.anchor);return new i([a,a.add(this.j)])},hitTest:function(b,d,c,e){b=this.getDisplayBoundingBox(b);d=new a(d,c);c=this.hitArea;return b.contains(d)&&(!c||c.hitTest(d.sub(b.topLeft),e))},getDisplayOffset:function(b,d,c){return(new a(d,c)).sub(b.geoToPixel(this.coordinate))},aa:function(a,b,d,c){b!=="zIndex"&&(this.Y|=b==="coordinate"?1:2);this._super(a,b,d,c)},Tc:function(b){var d="error";if(b.state===1)this.j=new a(b.width,b.height),this.Z("icon",this.icon,
2),d="load";this.dispatch(new c.Event({type:d,target:this,relatedTarget:b}))},getIconForRendering:function(a){var b=this.icon;a!==document&&(b=b.clone(a));b.state||b.prepare(this.Tc,this);return b},project:function(a){return this.qa[a.id]||(this.qa[a.id]=a.geoToMapPoints(h.stencil(h.LAT_LNG,[this.coordinate.latitude,this.coordinate.longitude])))}});if(nokia.maps.map.Marker.isNs)nokia.maps.map.Marker=f})();ovi.provide("nokia.maps.map.StandardMarker");
(function(){function f(a,b,d){a.J.set(b,d);if(b==="shape")a.j=a.J.j,a.set("anchor",a.J.anchor),a.set("hitArea",a.J.hitArea);return a.J[b]}var e=nokia.maps,c=e.util,b=e.map.Ra,e=nokia.maps.map.StandardMarker=new ovi.Class({Extends:nokia.maps.map.Marker,initialize:function(a,e){var d=this.J=new b(c.flatMerge({},e,1,b.ra));c.flatMerge(this,d,1,b.ra);this.j=d.j;this._super(a,c.flatMerge({},e,1,b.dd))},q:"standardmarker",shapeSetter:function(a){return f(this,"shape",a)},textSetter:function(a){return f(this,
"text",a)},textPenSetter:function(a){return f(this,"textPen",a)},penSetter:function(a){return f(this,"pen",a)},brushSetter:function(a){return f(this,"brush",a)},getIconForRendering:function(a){this.set("icon",this.J.getIcon());return this._super(a)}});c.flatMerge(e.prototype,b.prototype,!0,b.ra)})();ovi.provide("nokia.maps.map.component.panning.Drag");
(function(f){var e=f.map.component;e.panning.Drag=new ovi.Class({Extends:e.Component,Statics:{LMB:1,RMB:4,MMB:2},d:"panning.Drag",A:"0.0.0.1",initialize:function(c){function b(a){var b=a.dataTransfer,d=b&&b.getData("application/map-drag-type");b&&b.getData("application/map-drag-object");var b=a.deltaX,c=a.deltaY;if(d==="map"){if(b||c)g?g.moveBy(-b,-c,!0):f.pan(0,0,-b,-c);g&&(g.endMovement(),g=null);a.stopImmediatePropagation()}}function a(a){var b=a.dataTransfer,b=b&&b.getData("application/map-drag-type"),
d=a.deltaX,c=a.deltaY;if(b==="map"){if(d||c)g?g.moveBy(-d,-c,!0):f.pan(0,0,-d,-c);a.stopImmediatePropagation()}}function h(a){if(d.enabled&&d.dragButtons&1<<a.button){var b=f.getComponentById("panning.Kinetic"),c=a.dataTransfer,e=a.deltaX,h=a.deltaY;c.cursor="hand";c.lift=!1;c.setData("application/map-drag-type","map");c.setData("application/map-drag-object",f);c.setData("application/map-drag-object-offset",void 0);a.stopImmediatePropagation();d.useKineticPanning&&b?(g=b.startMovement(),g.moveBy(-e,
-h,!0)):(g=null,f.pan(0,0,-e,-h))}}var d=this,i=e.Component.prototype,f,g;d._super(ovi.extend({enabled:!0,useKineticPanning:!0},c));d.dragButtons=d.dragButtons||7;d.attach=function(c){i.attach.call(d,c);f=c;f.addListener("dragstart",h);f.addListener("drag",a);f.addListener("dragend",b)};d.detach=function(c){i.detach.call(d,c);f.removeListener("dragstart",h);f.removeListener("drag",a);f.removeListener("dragend",b)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.objects.DragMarker");
(function(f){var e=f.util.Point,f=f.map,c=f.component,b=f.Marker,a=b.prototype.q,h=f.StandardMarker.prototype.q;c.objects.DragMarker=new ovi.Class({Extends:c.Component,d:"objects.DragMarker",A:"0.0.0.1",dragSourceOpacity:1,dragIconOpacity:0.5,initialize:function(d){function i(d){var c=d.dataTransfer,g=c&&c.getData("application/map-drag-type"),i=c&&c.getData("application/map-drag-object");if((g===a||g===h)&&i instanceof b){if(i.getParent(o))c.dropEffect="none";else if(c.allows("move"))c.dropEffect=
"move";else{c.dropEffect="none";d.cancel();return}g=c.getData("application/map-drag-object-offset")||new e(0,0);i.set("coordinate",o.pixelToGeo(d.displayX-g.x+i.anchor.x,d.displayY-g.y+i.anchor.y));c.dropEffect!=="none"&&o.objects.add(i);d.cancel()}else c.dropEffect="none"}function f(b){var d=b.dataTransfer,c=d&&d.getData("application/map-drag-type"),e=d&&d.getData("application/map-drag-object");if(c===a||c===h)d.dropEffect=e.getParent(o)?"move":"copy",b.cancel()}function g(b){var d=b.dataTransfer,
c=d&&d.getData("application/map-drag-type"),e=d&&d.getData("application/map-drag-object");if(c===a||c===h)d.dropEffect=e.getParent(o)?"move":"copy",b.cancel()}function m(b){var d=b.dataTransfer,c=d&&d.getData("application/map-drag-type"),e=d&&d.getData("application/map-drag-object");if(c===a||c===h)e.removeListener("dragend",m,!0),d.dropEffect==="move"&&(dragMarkerParent=e.getParent(o),dragMarkerParent.objects.remove(e)),e.icon.opacity=1,e.Z("icon",e.icon,2),b.stopImmediatePropagation()}function k(a){var b=
a.dataTransfer;(b&&b.getData("application/map-drag-type"))===h&&a.stopImmediatePropagation()}function j(a){if(n.enabled){var d,c,g,h=a.target,i=a.dataTransfer;if(h instanceof b&&h.draggable)c=h.getDisplayBoundingBox(o),d=a.displayX-c.topLeft.x,c=a.displayY-c.topLeft.y,g=h.getIconForRendering(document),i.setDragImage(g.createElement(n.dragIconOpacity),-d,-c),h.icon.opacity=n.dragSourceOpacity,h.Z("icon",h.icon,2),i.setData("application/map-drag-type",h.q),i.setData("application/map-drag-object",h),
i.setData("application/map-drag-object-offset",new e(d,c)),i.effectAllowed="all",h.insertListener("dragend",m,!0),a.stopImmediatePropagation()}}var n=this,p=c.Component.prototype,o;n._super(ovi.extend({enabled:!0,useKineticPanning:!0},d));n.attach=function(a){p.attach.call(n,a);o=a;o.addListener("dragstart",j);o.addListener("drag",k);o.addListener("dragend",m);o.addListener("dragenter",g);o.addListener("dragover",f);o.addListener("drop",i)};n.detach=function(a){p.detach.call(n,a);o.removeListener("dragstart",
j);o.removeListener("drag",k);o.removeListener("dragend",m);o.removeListener("dragenter",g);o.removeListener("dragover",f);o.removeListener("drop",i)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.Behavior");
(function(f){var e=f.map.component;e.Behavior=new ovi.Class({Extends:e.Component,d:"Behavior",A:"0.0.0.1",initialize:function(){var c=this,b=ovi.bind,a,h,d,i,f,g,m,k;c.attach=function(j){c.mapDisplay=a=j;var j=b(a,a.addComponent),n=e.zoom,p=e.panning;h=n.MouseWheel&&j(new n.MouseWheel);d=n.DoubleClick&&j(new n.DoubleClick);i=n.DoubleTap&&j(new n.DoubleTap);f=n.Gesture&&j(new n.Gesture);g=p.Drag&&j(new p.Drag);m=p.Kinetic&&j(new p.Kinetic);k=e.objects.DragMarker&&j(new e.objects.DragMarker)};c.detach=
function(){delete c.mapDisplay;var e=b(a,a.removeComponent);h&&e(h);d&&e(d);i&&e(i);f&&e(f);g&&e(g);m&&e(m);k&&e(k);a=null}}})})(nokia.maps);ovi.provide("nokia.maps.behavior._packaging.package-all");})();
